config/routes.rb
Rails.application.routes.draw do
  
  resources :formularios
  resources :coctels
  resources :liquors
  resources :usuarios
  devise_for :userlogs
  #get 'home/index'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/formulario.rb
class Formulario < ApplicationRecord
    belongs_to :userlog
    has_many :liquor_formularios
    has_many :liquors, through: :liquor_formularios
    attr_accessor :liquor_favorito

    has_many :recomendaciones
    has_many :liquor_coctels, through: :recomendaciones
    attr_accessor :coctel_recomendado

    has_many :coctel_formularios
    has_many :coctels, through: :coctel_formularios

   
    def save_liquorsfavs
        return liquor_formularios.destroy_all if liquor_favorito.nil? || liquor_favorito.empty?
        
        liquor_formularios.where.not(liquor_id: liquor_favorito).destroy_all
        
        liquor_favorito.each do |liquor_id|
        
          LiquorFormulario.find_or_create_by(formulario: self, liquor_id: liquor_id)
        end 
      end

    

      
  

      

end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  before_action :authenticate_userlog!
  before_action :set_formulario, only: %i[ show edit update destroy ]
  before_action :correct_userlog, only: [:edit, :update, :destroy]

  # GET /formularios or /formularios.json
  def index
    @formularios = Formulario.all
  end

  # GET /formularios/1 or /formularios/1.json
  def show

   # @observar = Formulario.joins(:liquors).find_by(liquors: {marca: 'Absolut'})
    #@observar = @observar.peso_kg


    @prueba = Formulario.joins(:liquors).where("liquors.grados_alcohol > ?", 30).pluck(:nombre_drinker)

    @alcohol_tomado = 14

    #@nivel_alcohol: 0.08 0.2 0.4
    @nivel_alcohol = 0.08

  
    

    #Perfiles drinker
    if @formulario.perfil == "Conductor"
      @perfil_tomador = Liquor.find_by("grados_alcohol <= 29 ")
      @perfil_tomador = @perfil_tomador.nombre_licor
      @nivel_alcohol = 0.8
      
    elsif @formulario.perfil == "Moderado"
      @perfil_tomador = Liquor.find_by("grados_alcohol < 39 AND grados_alcohol > 30")
      @perfil_tomador = @perfil_tomador.nombre_licor
      @nivel_alcohol = 0.4
      
    else
      @perfil_tomador = Liquor.find_by("grados_alcohol > 39")
      @perfil_tomador = @perfil_tomador.nombre_licor
      @nivel_alcohol = 0.2
      
    end

    #@promedi= Coctel.where(liquor: 'Cerveza').average(:gramos_alcohol).to_f

   


    #Formula Widemark
    if @formulario.genero == "Masculino"
      #@wid = ((@alcohol_tomado/((@formulario.peso_kg*1000) * 0.68)) * 100) - (@formulario.horas_estadia * 0.015)
      @wid = (((@formulario.peso_kg)*0.68*0.1)/(@nivel_alcohol)) + (@formulario.horas_estadia * 0.015)
      @wid = @wid.to_i
    else
      #@wid = ((@alcohol_tomado/((@formulario.peso_kg*1000) * 0.55)) * 100) - (@formulario.horas_estadia * 0.015)
      @wid = (((@formulario.peso_kg)*0.55*0.1)/@nivel_alcohol) + (@formulario.horas_estadia * 0.015)
      @wid = @wid.to_i
    end

    @mostrar = @formulario.liquor_favorito

    

  end

  # GET /formularios/new
  def new
    #@formulario = Formulario.new
    @formulario = current_userlog.formularios.build
    @liquors = Liquor.all
  end

  # GET /formularios/1/edit
  def edit
    @liquors = Liquor.all
  end

  # POST /formularios or /formularios.json
  def create
    #@formulario = Formulario.new(formulario_params)
    @formulario = current_userlog.formularios.build(formulario_params)
    @liquors = Liquor.all
    @formulario.save_liquorsfavs

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to formulario_url(@formulario), notice: "Formulario was successfully created." }
        format.json { render :show, status: :created, location: @formulario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formularios/1 or /formularios/1.json
  def update
    respond_to do |format|
      if @formulario.update(formulario_params)
        format.html { redirect_to formulario_url(@formulario), notice: "Formulario was successfully updated." }
        format.json { render :show, status: :ok, location: @formulario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
    @formulario.save_liquorsfavs
  end

  # DELETE /formularios/1 or /formularios/1.json
  def destroy
    @formulario.save_liquorsfavs
    @formulario.destroy

    respond_to do |format|
      format.html { redirect_to formularios_url, notice: "Formulario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_userlog
    @formulario = current_userlog.formularios.find_by(id: params[:id])
    redirect_to formularios_path, notice: "No estas autorzado a editar este formulario" if @formulario.nil?
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario
      @formulario = Formulario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formulario_params
      params.require(:formulario).permit(:nombre_drinker, :estatura_cm, :peso_kg, :genero, :horas_estadia, :perfil, :presupuesto, :userlog_id, liquor_favorito: [])
    end
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_form.html.erb
<%= form_with(model: formulario) do |form| %>
  <% if formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
        <% formulario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_del_drinker %>
    <%= form.text_field :nombre_drinker %>
  </div>

  <div class="field">
    <%= form.label :estatura_en_cm %>
    <%= form.text_field :estatura_cm %>
  </div>

  <div class="field">
    <%= form.label :peso_en_kg %>
    <%= form.text_field :peso_kg %>
  </div>

  <div class="field">
    <%= form.label :genero %>
    <%= form.select :genero, options_for_select(["Masculino", "Femenino"]) %>
  </div>

  <div class="field">
    <%= form.label :horas_de_estadia %>
    <%= form.number_field :horas_estadia %>
  </div>

  <div class="field">
    <%= form.label :selecciona_tu_perfil %>
    <%= form.label :"Conductor: quiero beber lo suficiente para volver a salvo a casa"  %>
    <%= form.label :"Moderado: quiero beber lo suficiente para no tener resaca por la mañana" %>
    <%= form.label :"Alma de la fiesta: quiero beber hasta el agua de los floreros" %>
    <%= form.select :perfil, options_for_select(["Conductor", "Moderado",  "Alma de la fiesta"]) %>
  </div>

  <div class="field">
    <%= form.label :presupuesto_maximo_para_la_noche_en_dolares %>
    <%= form.select :presupuesto, options_for_select(["20", "50", "100"]) %>
  </div>

  <div class="field">
    <%= form.number_field :userlog_id, id: :formulario_userlog_id, value: current_userlog.id, type: :hidden %>
  </div>



  <div class="field">
    <%= form.label :selecciona_tus_licores_favoritos %>
    <div class="row">
     <% @liquors.each do |liquor| %>
      <label for="col-6 col-sm-3">
       <%= form.check_box :liquor_favorito, {multiple: true}, liquor.id, nil  %>
       <%= liquor.nombre_licor %>
       </label>
     <% end %>
    </div>
  </div>

  


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formularios/edit.html.erb
<h1>Editing Formulario</h1>

<%= render 'form', formulario: @formulario %>

<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', formularios_path %>

app/views/formularios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mis Formularios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre drinker</th>
      <th>Estatura cm</th>
      <th>Peso kg</th>
      <th>Genero</th>
      <th>Horas estadia</th>
      <th>Perfil</th>
      <th>Presupuesto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formularios.each do |formulario| %>
      <% if formulario.userlog == current_userlog %>
      <tr>
        <td><%= formulario.nombre_drinker %></td>
        <td><%= formulario.estatura_cm %></td>
        <td><%= formulario.peso_kg %></td>
        <td><%= formulario.genero %></td>
        <td><%= formulario.horas_estadia %></td>
        <td><%= formulario.perfil %></td>
        <td><%= formulario.presupuesto %></td>
        <td><%= link_to 'Ver recomendaciones', formulario %></td>
        <td><%= link_to 'Editar formulario', edit_formulario_path(formulario) %></td>
        <td><%= link_to 'Eliminar formulario', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'NNuevo Formulario', new_formulario_path %>

app/views/formularios/new.html.erb
<h1>New Formulario</h1>

<%= render 'form', formulario: @formulario %>

<%= link_to 'Back', formularios_path %>

app/views/formularios/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>
  Hola <%= @formulario.nombre_drinker %>
   te recomendamos: </strong>
</h1>

<!-- <p>
  <strong>Estatura cm:</strong>
  <%= @formulario.estatura_cm %>
</p>

<p>
  <strong>Peso kg:</strong>
  <%= @formulario.peso_kg %>
</p>


<p>
  <strong>Genero:</strong>
  <%= @formulario.genero %>
</p>

<p>
  <strong>Horas estadia:</strong>
  <%= @formulario.horas_estadia %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @formulario.perfil %>
</p>

<p>
  <strong>Presupuesto:</strong>
  <%= @formulario.presupuesto %>
</p>


<p>
  
  <strong>Exclusivamente:</strong>
  <%= @observar %>
  
</p>
-->

<p>
  
  <strong>Beber maximo <%= @wid %> cocteles </strong>
  
</p>

<p>
  
  <strong>Si quieres ser el <%= @formulario.perfil %> prueba cocteles con:</strong>
  <%= @perfil_tomador %>
  
</p>


<!--
<p>
  
  <strong>Exclusivamente:</strong>
  <%= @prueba.each do |prueba| %>
  <% end %>
  
</p>
-->



<p>
  <h4> <strong>Información de tus licores favoritos:</strong> </h4>
  <% @formulario.liquors.each do |liquor| %>
    
 
    <div class="card" style="width: 18rem;">
    <h5 class="card-title"><%= liquor.nombre_licor %></h5>
    <p class="card-text">

    
    
    <strong>Marca:</strong>
    <%= liquor.marca %>
  </p>
  
  <p>
    <strong>Grados de alcohol:</strong>
    <%= liquor.grados_alcohol %>
  </p>


  <p>
    <span class="btn btn-primary" >
    <%= link_to 'Ver cocteles disponibles', liquor, class:"text-white" %>
    </span>

  </p>
      
    </div>
    <br>
  <% end %>
  
</p>










<%= link_to 'Editar Formulario', edit_formulario_path(@formulario) %> |
<%= link_to 'Regresar', formularios_path %>