config/routes.rb
Rails.application.routes.draw do
  
  resources :formularios
  resources :coctels
  resources :liquors
  resources :usuarios
  devise_for :userlogs
  #get 'home/index'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coctel.rb
class Coctel < ApplicationRecord
    has_many :liquor_coctels
    has_many :liquors, through: :liquor_coctels

    has_many :coctel_formularios
    has_many :formularios, through: :coctel_formularios

    attr_accessor :liquor_principal

    def save_liquors
        return liquor_coctels.destroy_all if liquor_principal.nil? || liquor_principal.empty?
        
        liquor_coctels.where.not(liquor_id: liquor_principal).destroy_all
        
        liquor_principal.each do |liquor_id|
        
          LiquorCoctel.find_or_create_by(coctel: self, liquor_id: liquor_id)
        end
      end

end

app/controllers/coctels_controller.rb
class CoctelsController < ApplicationController
  before_action :authenticate_userlog!
  before_action :set_coctel, only: %i[ show edit update destroy ]

  

  # GET /coctels or /coctels.json
  def index
    @coctels = Coctel.all

    if params[:min_price].present?
      @coctels = @coctels.where("precio >= ?", params[:min_price])
    end
    
  end

  # GET /coctels/1 or /coctels/1.json
  def show
    @menores = Coctel.find_by("precio <= '10'")
  end

  # GET /coctels/new
  def new
    @coctel = Coctel.new
    @liquors = Liquor.all
  end

  # GET /coctels/1/edit
  def edit
    @liquors = Liquor.all
  end

  # POST /coctels or /coctels.json
  def create
    @coctel = Coctel.new(coctel_params)
    @liquors = Liquor.all
    @coctel.save_liquors
    

    respond_to do |format|
      if @coctel.save
        format.html { redirect_to coctel_url(@coctel), notice: "Coctel was successfully created." }
        format.json { render :show, status: :created, location: @coctel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coctel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coctels/1 or /coctels/1.json
  def update
    
    respond_to do |format|
      if @coctel.update(coctel_params)
        format.html { redirect_to coctel_url(@coctel), notice: "Coctel was successfully updated." }
        format.json { render :show, status: :ok, location: @coctel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coctel.errors, status: :unprocessable_entity }
      end
    end
    @coctel.save_liquors
  end

  # DELETE /coctels/1 or /coctels/1.json
  def destroy  
    @coctel.save_liquors
    @coctel.destroy

    respond_to do |format|
      format.html { redirect_to coctels_url, notice: "Coctel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coctel
      @coctel = Coctel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coctel_params
      params.require(:coctel).permit(:nombre_coctel, :gramos_alcohol, :precio, liquor_principal: [])
    end


end

app/helpers/coctels_helper.rb
module CoctelsHelper
end

app/views/coctels/_form.html.erb
<%= form_with(model: coctel) do |form| %>
  <% if coctel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coctel.errors.count, "error") %> prohibited this coctel from being saved:</h2>

      <ul>
        <% coctel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_coctel %>
    <%= form.text_field :nombre_coctel %>
  </div>

  <div class="field">
    <%= form.label :gramos_alcohol %>
    <%= form.text_field :gramos_alcohol %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :liquor_principal %>
    <div class="row">
     <% @liquors.each do |liquor| %>
      <label for="col-6 col-sm-3">
       <%= form.check_box :liquor_principal, {multiple: true}, liquor.id, nil  %>
       <%= liquor.nombre_licor %>
       </label>
     <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coctels/edit.html.erb
<h1>Editing Coctel</h1>

<%= render 'form', coctel: @coctel %>

<%= link_to 'Show', @coctel %> |
<%= link_to 'Back', coctels_path %>

app/views/coctels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocteles</h1>
<!--

<%= form_with url: coctels_path, method: :get do |form| %>

  <%= form.number_field :min_price, placeholder: t('.min_price'),
  onChange: 'this.form.requestSumbit()' %>
  <%= form.number_field :max_price, placeholder: t('.max_price'),
  onChange: 'this.form.requestSumbit()' %>
  <% end %>

  -->

<table>
  <thead>
    <tr>
      <th>Nombre coctel</th>
      <th>Gramos alcohol</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coctels.each do |coctel| %>
      <tr>
        <td><%= coctel.nombre_coctel %></td>
        <td><%= coctel.gramos_alcohol %></td>
        <td><%= coctel.precio %></td>
        <td><%= link_to 'Ver coctel', coctel %></td>
        
        <% if current_userlog.id == 4 %>
        <td><%= link_to 'Edit', edit_coctel_path(coctel) %></td>
        <td><%= link_to 'Destroy', coctel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_userlog.id == 4 %>
<%= link_to 'New Coctel', new_coctel_path %>
<% end %>

app/views/coctels/new.html.erb
<% if current_userlog.id == 4 %>
<h1>New Coctel</h1>

<%= render 'form', coctel: @coctel %>

<%= link_to 'Back', coctels_path %>
<% end %>

app/views/coctels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre coctel:</strong>
  <%= @coctel.nombre_coctel %>
</p>

<p>
  <strong>Gramos alcohol:</strong>
  <%= @coctel.gramos_alcohol %>
</p>


<p>
  <strong>Precio:</strong>
  <%= @coctel.precio %>
</p>


<% if current_userlog.id == 4 %>
<%= link_to 'Edit', edit_coctel_path(@coctel) %> 
<% end %>
<%= link_to 'Regresar', coctels_path %>