config/routes.rb
Rails.application.routes.draw do
  
  resources :formularios
  resources :coctels
  resources :liquors
  resources :usuarios
  devise_for :userlogs
  #get 'home/index'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/liquor.rb
class Liquor < ApplicationRecord
    has_many :liquor_coctels
    has_many :coctels, through: :liquor_coctels

    has_many :liquor_formularios
    has_many :formularios, through: :liquor_formularios
end

app/controllers/liquors_controller.rb
class LiquorsController < ApplicationController
  before_action :authenticate_userlog!
  before_action :set_liquor, only: %i[ show edit update destroy ]

  # GET /liquors or /liquors.json
  def index
    @liquors = Liquor.all
  end

  # GET /liquors/1 or /liquors/1.json
  def show

  end

  # GET /liquors/new
  def new
    @liquor = Liquor.new
  end

  # GET /liquors/1/edit
  def edit
  end

  # POST /liquors or /liquors.json
  def create
    @liquor = Liquor.new(liquor_params)

    respond_to do |format|
      if @liquor.save
        format.html { redirect_to liquor_url(@liquor), notice: "Liquor was successfully created." }
        format.json { render :show, status: :created, location: @liquor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @liquor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquors/1 or /liquors/1.json
  def update
    respond_to do |format|
      if @liquor.update(liquor_params)
        format.html { redirect_to liquor_url(@liquor), notice: "Liquor was successfully updated." }
        format.json { render :show, status: :ok, location: @liquor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @liquor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquors/1 or /liquors/1.json
  def destroy
    @liquor.destroy

    respond_to do |format|
      format.html { redirect_to liquors_url, notice: "Liquor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liquor
      @liquor = Liquor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liquor_params
      params.require(:liquor).permit(:nombre_licor, :marca, :grados_alcohol)
    end
end

app/helpers/liquors_helper.rb
module LiquorsHelper
end

app/views/liquors/_form.html.erb
<%= form_with(model: liquor) do |form| %>
  <% if liquor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liquor.errors.count, "error") %> prohibited this liquor from being saved:</h2>

      <ul>
        <% liquor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_licor %>
    <%= form.text_field :nombre_licor %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca %>
  </div>

  <div class="field">
    <%= form.label :grados_alcohol %>
    <%= form.text_field :grados_alcohol %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/liquors/edit.html.erb
<h1>Editing Liquor</h1>

<%= render 'form', liquor: @liquor %>

<%= link_to 'Show', @liquor %> |
<%= link_to 'Back', liquors_path %>

app/views/liquors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liquors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre licor</th>
      <th>Marca</th>
      <th>Grados alcohol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liquors.each do |liquor| %>
      <tr>
        <td><%= liquor.nombre_licor %></td>
        <td><%= liquor.marca %></td>
        <td><%= liquor.grados_alcohol %></td>
        <td><%= link_to 'Ver Cocteles con este licor', liquor %></td>
        <% if current_userlog.id == 4 %>
        <td><%= link_to 'Edit', edit_liquor_path(liquor) %></td>
        <td><%= link_to 'Destroy', liquor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_userlog.id == 4 %>
<%= link_to 'New Liquor', new_liquor_path %>
<% end%>

app/views/liquors/new.html.erb
<h1>New Liquor</h1>

<%= render 'form', liquor: @liquor %>

<%= link_to 'Back', liquors_path %>

app/views/liquors/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%= @liquor.nombre_licor %> </h5>
    <p class="card-text">
    <p>
  <strong>Marca:</strong>
  <%= @liquor.marca %>
</p>


<p>
  <strong>Grados alcohol:</strong>
  <%= @liquor.grados_alcohol %>
</p>
    </p>
    </div>
    </div>

    <div>
    
</div>

  
    <p>
  <strong>Cocteles para tu seleccion:</strong>
  <% @liquor.coctels.each do |coctel| %>
    
 
    <div class="card" style="width: 18rem;">
    <h5 class="card-title"><%= coctel.nombre_coctel %></h5>
    <p class="card-text">
    
    <strong>Gramos de alcohol:</strong>
    <%= coctel.gramos_alcohol %>
  </p>
  
  <p>
    <strong>Precio:</strong>
    <%= coctel.precio %>
  </p>
  
      
    </div>
    <br>
  <% end %>
  
</p>