config/routes.rb
Rails.application.routes.draw do
  
  resources :formularios
  resources :coctels
  resources :liquors
  resources :usuarios
  devise_for :userlogs
  #get 'home/index'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_userlog!
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario fue creado correctamente." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario fue editado correctamente." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario fue eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:id_usuario, :nombre, :apellido, :correo, :telefono)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_usuario %>
    <%= form.number_field :id_usuario %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Regresar', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Id usuario</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id_usuario %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.telefono %></td>
        <td><%= link_to 'Mostrar', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Eiminar', usuario, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Regresar', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id usuario:</strong>
  <%= @usuario.id_usuario %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @usuario.telefono %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Regresar', usuarios_path %>